### PR TITLE
move quiver into "quiver" sub-directory

### PR DESCRIPTION
**Pull request by yjbanov**

### CODE REVIEW

**Comment by justinfagnani** [comment]
Won't this prevent using quiver as a git dependency? Or does pub have subdirectory sorry now?

**Comment by yjbanov** [comment]
@justinfagnani good point. How important do you think it is, given that turning a git dependency to a path dependency is one `git clone` away?

**Comment by justinfagnani** [comment]
I think it's pretty important for cases where a fix is on master or another branch and someone would like to try it out. Asking to install via git might be a bit much.

**Comment by zoechi** [comment]
What's the reasoning behind this change anyway?

**Comment by yjbanov** [comment]
@zoechi, this is preparation for the split into multiple packages. The idea is we move quiver one level down and create multiple packages at the top level. Then quiver would reexport stuff from these packages.

**Comment by justinfagnani** [comment]
Why not create new repos? Or, I'm sure many things could move into existing packages like async, or collection.

**Comment by yjbanov** [comment]
We'll do new repos on https://github.com/QuiverDart. Closing this.

**Pull request closed without merging**
