### PR TITLE
better typing in cache

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by cbracken** [comment]
lgtm

**Comment by a14n** [comment]
@cbracken I can't merge:

>Only those with write access to this repository can merge pull requests.
>You're not authorized to merge this pull request.

**Comment by cbracken** [comment]
Thanks for letting me know -- taking a look at settings!

**Comment by cbracken** [comment]
Hrm. It *claims* that you have write access... 
screen shot 2017-10-16 at 14 18 14

I'll do some digging to see if there's anything else I need to do. Maybe there's an organisation-level policy or something I missed. For now I'll merge these then. Thanks again!

**Pull request merged**
