### PR TITLE
Add String Extensions 

### LINKED ISSUE #578: Add Extension methods to strings and others
It would be nice to convert methos such as `isBlank` to `"myString".isBlank`, using the new Extension methods from Dart 2.7.

### PR DESCRIPTION
**Pull request by feinstein**
Add String Extensions and closes #578.

### CODE REVIEW

**Comment by feinstein** [comment]
@cbracken why was this closed and the 3.0v branch deleted? Are you planning on another path to include null safety?

**Comment by cbracken** [comment]
Strange -- I didn't explicitly close this. The master branch is currently 3.0.1 and has null safety enabled. A couple of days ago I did a bunch of branch cleanup and deleted the `null_safety` and `3.0.0-dev` branches. I assume that must have been what triggered the PR to close; apologies for missing this! I'll see if I can rebase your commit locally against master and re-open (and also follow-up on it now that 3.0.0 has landed on master)

**Comment by cbracken** [comment]
Alright did a rebase against master, fixed a couple merge conflicts and fixed a couple nullability annotations and have pushed the commit here:
https://github.com/google/quiver-dart/commit/4f8308411f6088cba7c1104727905183123a785a

If you want to open a new pull-request based off master, please go for it. You could create a new branch off tip-of-tree master and cherry-pick 4f8308411f6088cba7c1104727905183123a785a then you're set.

Apologies again for dropping the ball on this!

**Comment by feinstein** [comment]
@cbracken my git fu isn't that strong I guess.... how can I cherry-pick that commit, since it was uploaded without a branch? I can't manage to see it on my local repo. Is it there a special command? Does git fetch/pull "downloads" commits that aren't in a branch?

**Comment by feinstein** [comment]
Never mind, I figured it out, I just had to do a `git fetch 4f8308411f6088cba7c1104727905183123a785a` and then cherry pick it.

**Pull request closed without merging**
