### PR TITLE
Remove pattern/glob. Use glob package: pub.dartlang.org/packages/glob.

### PR DESCRIPTION
**Pull request by cbracken**
Addresses #207.

### CODE REVIEW

**Comment by justinfagnani** [comment]
README.md needs updating too

**Comment by justinfagnani** [comment]
Actually, this doesn't look good to me. package:glob can't be used in the browser.

**Comment by cbracken** [comment]
Agreed - not merging till the performance and dependency issues in package:glob are addressed.

**Comment by seaneagan** [comment]
@cbracken @justinfagnani I filed an issue for the dart:io dependency [here](https://github.com/dart-lang/glob/issues/1).  It would be nice to have a bug for the performance issues as well.  Would one of you either be able to file that, or share what benchmarks you ran?

**Pull request closed without merging**
