### PR TITLE
Fix: MultiMap's update signature

### PR DESCRIPTION
**Pull request by srawlins**
My bad. This signature was wrong.

Patch or + version change? 0.27.1? 0.27.0+1?

### CODE REVIEW

**Comment by srawlins** [comment]
CC @cbracken

**Comment by cbracken** [comment]
Technically it should be 0.28.0 since it's a breaking change. Can you update the changelog?

**Comment by srawlins** [comment]
Done!

**Comment by yjbanov** [comment]
lgtm

**Pull request merged**
