### PR TITLE
#245 Update to new test package and new matcher

### PR DESCRIPTION
**Pull request by zoechi**

### CODE REVIEW

**Comment by cbracken** [comment]
One minor changelog nit, other than that, LGTM. Thanks!

**Comment by zoechi** [comment]
Ok, didn't know how you usually do this.
fixed.

**Comment by cbracken** [comment]
No worries, some days, I hardly know how we do it either ;)

**Comment by cbracken** [comment]
Merged as 0b10be4cdbfbaa8b8285253a1cc9feba046a32bc.

**Comment by zoechi** [comment]
I hope you are going to publish the updated version soon. The dependency constraint on matcher  prevents me publishing several of my packages because I currently need to use dependency overrides.
Thanks

**Comment by cbracken** [comment]
Will do today, I need to revert part of it (the change moving off travis.sh) since it results in the loss of coverage collection. Once that's in, I'll cut a new release.

**Comment by cbracken** [comment]
Also reduced the matcher lower bound back to 0.10.0 since that's all we require for the code in lib/testing/equality.dart. We'll still get 0.12.0 due to dev deps, but we won't be forcing that lower bound on dependents of Quiver.

**Comment by cbracken** [comment]
Published [v0.21.3+1](https://pub.dartlang.org/packages/quiver).

**Comment by zoechi** [comment]
Great.
I increased the lower bound to help pub a bit. I sometimes have troubles
with `pub upgrade` when there are too many possibilities.

Mit freundlichen Grüßen

Günter Zöchbauer
guenter@gzoechbauer.com
+43 (699) 10 18 87 15

**Pull request closed without merging**
